version: "3"

services:

  react:
    container_name: docker_test
    image: node:18-alpine
    build: ./
    volumes:
      - "./:/app"
    working_dir: /app
    command: "npm start"
    ports:
      - "5000:5000"